config/routes.rb
 Rails.application.routes.draw do

  namespace :admin do
    get 'pict_comments/index'
  end
  namespace :admin do
    get 'comments/index'
  end
  namespace :admin do
    # get 'contacts/index'
    # get 'contacts/show'
    resources :contacts, only: [:index, :show]
  end
  namespace :admin do
    # get 'user_pages/index'
    # get 'user_pages/show'
    # get 'user_pages/edit'
    resources :user_pages, only: [:index, :show, :edit, :update]
  end
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
     sessions: "admin/sessions"
  }
  devise_for :users, skip: [:passwords] ,controllers: {
    registrations: "user/registrations",
  sessions: 'user/sessions'
  }

  scope module: :user do
    root to: 'homes#top'
    get 'homes/about'
    get 'homes/warning'

    resources :notifications, only: :index
    delete 'notifications/destroy_all'

    resources :contacts, only: [:new, :create]
    post 'contacts/confilm', to: 'contacts#confilm', as: 'confilm'
    post 'contacts/back', to: 'contacts#back', as: 'back'
    get 'done', to: 'contacts#done', as: 'done'

    resources :user_pages, only: [:index, :show, :edit, :update] do
      resource :relationships, only: [:create, :destroy]
      # フォローする
      get 'followings' => 'relationships#followings', as: 'followings'
      # フォローされる
      get 'followers' => 'relationships#followers', as: 'followers'
    end
    get 'user/user_page/:id/check' => 'user_pages#check', as: 'check'
    patch 'user/user_page/:id/withdraw' => 'user_pages#withdraw', as: 'withdraw'
    # resources :bookmarks, only: [:index]

    resources :novels do
      member do
        get 'draft'
      end
      resource :bookmarks, only: [:create, :destroy]
      resources :comments, only: [:create, :destroy]
    end


    resources :picts do
      resource :pict_bookmarks, only: [:create, :destroy]
      resources :pict_comments, only: [:create, :destroy]
    end

    resources :messages, only: [:create]
    resources :rooms, only: [:create, :index, :show]

  end

  namespace :admin do
    get 'homes/top'
  end

end

app/models/novel.rb
class Novel < ApplicationRecord
  belongs_to :user
  has_one_attached :image
  has_many :comments, dependent: :destroy
  has_many :bookmarks, dependent: :destroy
  has_many :write_tags, dependent: :destroy
  has_many :tags, through: :write_tags,dependent: :destroy
  # 閲覧数
  has_many :read_counts, dependent: :destroy
  
  # 小説でいいねもらった時の通知
  has_many :notifications, dependent: :destroy


  # 一覧の新着順と古い順
  scope :latest, -> {order(created_at: :desc)}
  scope :old, -> {order(created_at: :asc)}


def save_tags(savenovel_tags)
       current_tags = self.tags.pluck(:name) unless self.tags.nil?
       old_tags = current_tags - savenovel_tags
       new_tags = savenovel_tags - current_tags
  
       old_tags.each do |old_name|
       self.tags.delete Tag.find_by(name: old_name)
       end
       
       new_tags.each do |new_name|
       novel_tag = Tag.find_or_create_by(name: new_name)
       self.tags << novel_tag
      end
end
      


   def bookmarked_by?(user)
     bookmarks.exists?(user_id: user.id)
   end


  with_options presence: true do
    validates :text_body
    validates :title
  end
  
  
  # 通知
  
  def create_notification_by(current_user)
    notification = current_user.active_notifications.new(
      novel_id: id,
      visited_id: user_id,
      action: "bookmark"
      )
      notification.save if notification.valid?
  end
  
  def create_notification_comment!(current_user, comment_id)
    # 自分以外にコメントしている人をすべて取得し、全員に通知を送る
    temp_ids = Comment.select(:user_id).where(novel_id: id).where.not(user_id: current_user.id).distinct
    temp_ids.each do |temp_id|
      save_notification_comment!(current_user, comment_id, temp_id['user_id'])
    end
    
    # まだ誰もコメントしていない場合は、投稿者に通知を送る
    save_notification_comment!(current_user, comment_id, user_id) if temp_ids.blank?
  end
  
  def save_notification_comment!(current_user, comment_id, user_id) if temp_ids.blank?
    # コメントは複数回することが考えられるため、１つの投稿に複数回通知する
    notification = current_user.active_notifications.new(
      novel_id: id,
      comment_id: comment_id,
      visited_id: visited_id,
      action: 'comment'
      )
       # 自分の投稿に対するコメントの場合は、通知済みとする
       if notification.visiter_id == notification.visited_id
         notification.checked = true
       end
       notification.save if notification.valid?
       end
  end
  
  
    def get_image
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg' )
    end
    image
    end


end

app/controllers/user/bookmarks_controller.rb
class User::BookmarksController < ApplicationController
  # before_action :set_user, only: [:index]

  def index
    bookmarks = Bookmark.where(user_id: @user.id).pluck(:novel_id)
    @bookmark_novels = Novel.find(bookmarks)
    # @bookmark_picts = Pict.find(bookmarks)
  end

  def create
    @novel = Novel.find(params[:novel_id])
    
    @bookmark = current_user.bookmarks.new(novel_id: @novel.id)
    @bookmark.save
    
    # 通知の作成
    @novel.create_notification_by(current_user)
    respond_to do |format|
      format.html {redirect_to request.referrer}
        format.js
    end
    
  end

  def destroy
    @novel = Novel.find(params[:novel_id])
    @bookmark = current_user.bookmarks.find_by(novel_id: @novel.id)
    @bookmark.destroy
  end

  private

  # def set_user
  #   @user = User.find(params[:id])
  # end

end

app/controllers/user/comment_controller.rb
class User::CommentController < ApplicationController

  def create
    @novel = Novel.find(params[:novel_id])
    @pict = Pict.find(params[:pict_id])
    @comment = current_user.comment.new(novel_id: @novel.id, pict_id: @pict.id)
    @comment.save
  end

  def destroy
    @novel = Novel.find(params[:novel_id])
    @pict = Pict.find(params[:pict_id])
    Comment.find(params[:id]).destroy
  end


  private

  def comment_params
    params.require(:comment).permit(:comment)
  end

end

app/controllers/user/comments_controller.rb
class User::CommentsController < ApplicationController

  def create
    @novel = Novel.find(params[:novel_id])
    @comment = current_user.comments.new(novel_id: @novel.id, comment: comment_params[:comment])
    @comment.score = Language.get_data(comment_params[:comment])
    if @comment.save!
    # 通知の作成
    @comment.create_notification_comment!(current_user, @novel.user, @novel.id)
    end
    
    
  end

  def destroy
    @novel = Novel.find(params[:novel_id])
    Comment.find(params[:id]).destroy
  end


  private

  def comment_params
    params.require(:comment).permit(:comment)
  end

end

app/controllers/user/confirmations_controller.rb
# frozen_string_literal: true

class User::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/user/contacts_controller.rb
class User::ContactsController < ApplicationController
  def new
    @contact = Contact.new
  end
  
  # 確認画面を作成する場合はこのような記述になるかと思います。
  # newアクションから入力内容を受け取り、
  # 送信ボタンを押されたらcreateアクションを実行します
  
  def confilm
    @contact = Contact.new(contact_params)
    if @contact.invalid?
      render :new
    end
  end
  
  # 入力内容に誤りがあった場合、
  # 入力内容を保持したまま前のページに戻るのが当たり前になっているかと思いますが、
  # backアクションを定義することで可能となります。
  def back
    @contact = Contact.new(contact_params)
    render :new
  end
  
  # 実際に送信するアクションになります。
  # ここで初めて入力内容を保存します。
  def create
    @contact = Contact.new(contact_params)
    if @contact.save
      # ContactMailer.send_mail(@contact).deliver_now
      redirect_to done_path
    else
      render :new
    end
  end
  
  # 送信完了画面
  def done
  end
  
  private
  
  
  def contact_params
    params.require(:contact)
          .permit(:email,
                  :name,
                  :nickname,
                  :subject,
                  :message
                 )
  end
  
end

app/controllers/user/homes_controller.rb
class User::HomesController < ApplicationController
  def top
     @q_pict = PictTag.ransack(params[:q])
     if params[:latest]
      @picts = Pict.where(privacy: "1").latest.page(params[:page])
     elsif params[:old]
      @picts = Pict.old.where(privacy: "1").page(params[:page])
     else
      @picts = Pict.where(privacy: "1").page(params[:page])
     end
     
      @q = Tag.ransack(params[:q])
      if params[:latest]
      @novels = Novel.latest.where(privacy: "1").page(params[:page])
      elsif params[:old]
      @novels = Novel.old.where(privacy: "1").page(params[:page])
      else
      @novels = Novel.where(privacy: "1").page(params[:page])
      end
     
  end

  def about
  end

  def warning
  end

end

app/controllers/user/messages_controller.rb
class User::MessagesController < ApplicationController
  before_action :authenticate_user!
  
  def create
     message = Message.new(message_params)
    message.user_id = current_user.id
    if message.save
      redirect_to room_path(message.room)
    else
      redirect_back(fallback_location: root_path)
    end
  end
  
  private
  
  def message_params
    params.require(:message).permit(:room_id, :body)
  end
  
end

app/controllers/user/notifications_controller.rb
class User::NotificationsController < ApplicationController
  
  def index
    #current_userの投稿に紐づいた通知一覧
    @notifications = current_user.passive_notifications
    #@notificationの中でまだ確認していない(indexに一度も遷移していない)通知のみ
    @notifications.where(checked: false).each do |notification|
      notification.update(checked: true)
    end
  end
  
  def destroy_all
    # 通知を全削除
    @notifications = current_user.passive_notifications.destroy_all
    redirect_to notifications_path
  end
  
  
end

app/controllers/user/novels_controller.rb
class User::NovelsController < ApplicationController
  # 自分以外の人が他人の小説を編集させないようにするコード
  before_action :ensure_novel, only:[:edit, :update, :destroy]

  def new
    @novel_new = Novel.new
  end

  def create
    # 下書きを後で追加する
    @novel_new = Novel.new(novel_params)
    @novel_new.user_id = current_user.id
    
     tag_list = params[:novel][:tag_ids].split(',')
     
     
    if @novel_new.save
      @novel_new.save_tags(tag_list)
      flash[:notice] = "小説が投稿されました"
      redirect_to novel_path(@novel_new.id)
    else
      @user = current_user
      @novels = @user.novels
      render :new
    end

  end

  def show
    @novel = Novel.find(params[:id])
    @comment = Comment.new
    @user = @novel.user
    # 閲覧数を新しく作成し、小説ID、ユーザーをcurrent_user = つまり自分のIDを入力
    if user_signed_in?
    current_user.read_counts.create(novel_id: @novel.id)
    end

  end

  def index
    @q = Tag.ransack(params[:q])
    if params[:latest]
      @novels = Novel.latest.where(privacy: "1").page(params[:page])
    elsif params[:old]
      @novels = Novel.old.where(privacy: "1").page(params[:page])
      
    elsif params[:q].present?
      
      @novels = Novel.where(id: WriteTag.where(tag_id: @q.result.order(created_at: :desc).pluck(:id)).pluck(:novel_id)).where(privacy: "1").page(params[:page]) || Novel.where(privacy: "1").page(params[:page])
      
    else
      @novels = Novel.where(privacy: "1").page(params[:page])
    end
  end
  
  # def draft
  #   @novel = Novel.find(params[:id])
  #   if @novel.display == "1"
  #     @novel.update(display: 0)
  #     redirect_to novel_path(@novel)
  #   else
  #     @novel.update(display: 1)
  #     redirect_to novel_path(@novel)
  #   end
  # end
  

  def edit
    @novel = Novel.find(params[:id])
    @tag_list = @novel.tags.pluck(:name).join(",")
  end

  def update
    @novel = Novel.find(params[:id])
    @tag_list = params[:novel][:tag_ids].split(',')
    
    if @novel.update(novel_params)
      @novel.save_tags(@tag_list)
      flash[:notice] = "小説が更新されました"
      redirect_to novel_path(@novel.id)
    else
      render :edit
    end
  end

  def destroy
    novel = Novel.find(params[:id])
    novel.destroy
    # 自分のページのインデックスに飛ぶようにゆくゆくする
    redirect_to novels_path
  end

private

def novel_params
  params.require(:novel).permit(:title, :text_body, :image, :caption, :privacy)
end

def ensure_novel
  @novels = current_user.novels
  @novel = @novels.find_by(id: params[:id])
  # 自分以外の小説の情報合致していないとunlessになる
  redirect_to novels_path unless @novel
  # unlessだった場合自分の小説一覧に飛ぶ
end


end

app/controllers/user/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class User::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/user/passwords_controller.rb
# frozen_string_literal: true

class User::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/user/pict_bookmarks_controller.rb
class User::PictBookmarksController < ApplicationController
   before_action :set_user, only: [:index]

  # def index
  #   bookmarks = Bookmark.where(user_id: @user.id).pluck(:pict_id)
  #   @bookmark_picts = Pict.find(bookmarks)
  #   # @bookmark_picts = Pict.find(bookmarks)
  # end

  def create
    @pict = Pict.find(params[:pict_id])
    @pict_bookmark = current_user.pict_bookmarks.new(pict_id: @pict.id)
    @pict_bookmark.save
    # 通知の作成
    @pict.create_notification_by(current_user)
    respond_to do |format|
      format.html {redirect_to request.referrer}
        format.js
    end
  end

  def destroy
    @pict = Pict.find(params[:pict_id])
    @pict_bookmark = current_user.pict_bookmarks.find_by(pict_id: @pict.id)
    @pict_bookmark.destroy
  end

  private

  # def set_user
  #   @user = User.find(params[:id])
  # end

end

app/controllers/user/pict_comments_controller.rb
class User::PictCommentsController < ApplicationController
  def create
    @pict = Pict.find(params[:pict_id])
    @comment = current_user.pict_comments.new(pict_id: @pict.id, comment: pict_comment_params[:comment])
    @comment.score = Language.get_data(pict_comment_params[:comment])
    if @comment.save!
        # 通知の作成
    @comment.create_notification_pict_comment!(current_user, @pict.user, @pict.id)
    end
  end

  def destroy
    @pict = Pict.find(params[:pict_id])
    PictComment.find(params[:id]).destroy
  end


  private

  def pict_comment_params
    params.require(:pict_comment).permit(:comment)
  end
end

app/controllers/user/registrations_controller.rb
# frozen_string_literal: true

class User::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/views/user/novels/_novel_index.html.erb
<% novels.each do |novel| %>
<%# if novel.privacy == "1" %>
<%# elsif novel.privacy == "2" && novel.user.id == user_signed_in? && current_user.id %>

<table class="table table-hover table-inverse">

  <tbody>

    <tr>
      <td class="novel_tag">
        <%= link_to novel_path(novel.id) do %>
        <%= image_tag novel.get_image, size: "100x100" %>
        <% end %>
      </td>
      <td class="novel_tag">
        <!--投稿ユーザーのアイコンとリンク-->
        <%= link_to user_page_path(novel.user.id) do %>
        <%= image_tag novel.user.get_profile_image(50,50), class: "mt-3 rounded-circle" %><%= novel.user.nickname %>
        <% end %>
      </td>
      <td class="novel_caption">
        <!--最初の1行30文字くらいで…を入れて見せないようにする。詳細ページで全部見れるようにする。-->
        <%= novel.caption%>
      </td>

      <td class="novel_tag">
        <% novel.tags.each do |tag| %>
          <span><%= tag.name %></span>
          <% end %>
      </td>

    </tr>


  </tbody>
</table>
<%# end %>
<% end %>

<%= paginate novels, theme: 'twitter-bootstrap-4' %>

app/views/user/novels/edit.html.erb
<h1>小説の編集</h1>

<%= form_with model: @novel do |f| %>

<div class="form-group">
<label for="novel-title">Title</label>
<%= f.text_field :title, class: "form-control" %>
</div>

<div class="form-group">
<label>本文</label>
<%= f.text_area :text_body, class: "form-control" %>
</div>

<div class="form-group">
  <label>キャプション</label>
  <%= f.text_area :caption, class: "form-control" %>
</div>

<div class="form-group">
<label for="inputImage">Image</label>
<%= f.file_field :image, placeholder: "プロフィール画像", accept: "image/*", class: "form-control-file" %>
</div>

  <div class="form-group">
    <%= f.select :privacy, [["公開",1],["非公開",2]], include_blank: "選択してください" %>
  </div>
  
  <!--タグの部分のみ抜粋-->
  <div class="form-group">
  <%= f.text_field :tag_ids, class: "form-control", value: @tag_list,\
   placeholder: "タグをつける。複数つけるには','で区切ってください。" %>
  </div>

<div class="form-group">
<%= f.submit '更新する', class: "btn btn-success" %>
</div>

<%= link_to "Show", novel_path(@novel.id) %>

<% end %>
</div>

app/views/user/novels/index.html.erb
<h1>小説一覧</h1>

<p>
  <%= link_to '小説新着順', novels_path(latest: "true") %>
  |<%= link_to '小説古い順', novels_path(old: "true") %>
</p>

<%= search_form_for @q, url: novels_path do |f| %>
<%= f.search_field :name_cont_any, placeholder: 'タグ検索' %>
<%= f.submit %>
<% end %>
<%= link_to "タグをリセットする", novels_path, class: "btn btn-info" %>

<%= render 'novel_index', novels: @novels %>

app/views/user/novels/new.html.erb
<div class="container mt-5">
        <div class="row">
          <div class="col">

<h1>小説投稿ページ</h1>
<% if user_signed_in? %>
<%= render 'layouts/errors', obj: @novel_new %>
<%= form_with model: @novel_new do |f| %>

<table class="table">

<div class="form-group">
  <%= f.text_field :title, placeholder: "タイトル", class: 'form-control' %>
</div>
  <!--別ページにリロードなしで行けて個別に書ける、下書き保存が出来る-->
  <div class="form-group">
  <%= f.text_area :text_body, placeholder: "本文", class: 'form-control' %>
  </div>

 <div class="form-group">
  <%= f.text_area :caption, placeholder: "小説の説明、あらすじなど", class: 'form-control' %>
 </div>
  <!--表紙アップロードにする。-->
  <div class="form-group">
    <%= f.label :image, "表紙画像アップロード" %><br>
    <%= f.file_field :image, placeholder: "小説の表紙", accept: "image/*", class: "form-control-file" %>
  </div>

  <div class="form-group">
    <%= f.select :privacy, [["公開",1],["非公開",2]], include_blank: "選択してください" %>
  </div>

  <!--タグの部分のみ抜粋-->
  <div class="form-group">
    タグをつける。複数つけるには','で区切ってください。
  <%= f.text_field :tag_ids, class: "form-control", id: 'tag_ids',\
   placeholder: "タグをつける。複数つけるには','で区切ってください。" %>
  </div>
  
  <div class="submit">
  <%= f.submit '小説を投稿する', name: "create" %>
  </div>
  
  <br>
<%= link_to "投稿の際はこちらを守っていただけますようお願いいたします。", homes_warning_path, class: "text-danger" %>

</table>
<% end %>
<% else %>
             <p>
                <%= link_to "投稿をするには新規登録をお願いします", new_user_registration_path, class: "text text-warning" %>
             </p>
             <p>
                <%= link_to "登録済みの方はこちらからログインをお願いいたします。", new_user_session_path %>
             </p>
              
<% end %>

</div>


  </div>
</div>

app/views/user/novels/show.html.erb
<h1><%= @novel.title %>の小説</h1>
<table class="table">
  <tbody>
 <tr>
  <td>
    <%= link_to user_page_path(@user.id) do %>

    <%= image_tag @user.get_profile_image(100,100), class: "mt-3 rounded-circle" %>
  <br>
  <%= @user.nickname %>
  <% end %>
  </td>

  <td><%= link_to novel_path(@novel.id) do %>
    <%= @novel.title %>
    <% end %>
    </td>

  <td><%= @novel.caption %></td>
  <!--<td>-->
          <% @novel.tags.each do |tag| %>
          <span><%= tag.name %></span>
          <% end %>
  <!--      </td>-->

      <td class="bookmarks_button_<%= @novel.id %>">
        <%= render 'user/bookmarks/bookmark-btn', novel: @novel %>
      </td>

       <td>
          <p>コメント数:<%= @novel.comments.count %></p>
        </td>


  <% if @novel.user == current_user %>





          <td><%= link_to edit_novel_path(@novel.id), class: "btn btn-sm btn-success" do %>
          Edit<% end %></td>
          <td><%= link_to novel_path(@novel.id), method: :delete, "data-confirm" => "本当に消しますか？", class: "btn btn-sm btn-danger" do %>
          Destroy<% end %></td>

  <% else %>
     <td></td>
     <td></td>



 <% end %>
  </tr>

  <tr>
    <td>
      <%= @novel.text_body %>
    </td>
  </tr>

 </tbody>
</table>


<div class="comment_index">
  <%= render 'user/comments/comment-index', novel: @novel %>
</div>
<div class="comment_form">
<%= render 'user/comments/form', novel: @novel, comment: @comment %>
</div>






 </div>
  </div>
</div>